list: $/eduzoneco/management/models/lessonstatus/columns.yaml
modelClass: Eduzoneco\Management\Models\LessonStatus
title: LessonStatuses
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'eduzoneco/management/lessonstatuses/update/:id'
