list: $/eduzoneco/management/models/coursestatus/columns.yaml
modelClass: Eduzoneco\Management\Models\CourseStatus
title: CourseStatuses
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'eduzoneco/management/coursestatuses/update/:id'
